pipeline:

  deploy_to_notprod:
    image: quay.io/ukhomeofficedigital/kd
    environment:
      - KUBE_NAMESPACE=dq-apps-notprod
      - INSECURE_SKIP_TLS_VERIFY=true
    commands:
      - export KUBE_TOKEN=$$NOTPROD_KUBE_TOKEN
      - export KUBE_SERVER=$$NOTPROD_KUBE_SERVER
      - export AWS_ACCESS_KEY_ID=$$NOTPROD_AWS_ACCESS_KEY_ID
      - export AWS_SECRET_ACCESS_KEY=$$NOTPROD_AWS_SECRET_ACCESS_KEY
      - export BUCKET=$$NOTPROD_BUCKET
      - export START_DATE=$$NOTPROD_START_DATE
      - export END_DATE=$$NOTPROD_START_DATE
      - kd -f secrets.yaml -f deployment.yaml
    secrets:
      - NOTPROD_KUBE_TOKEN
      - NOTPROD_KUBE_SERVER
      - NOTPROD_AWS_ACCESS_KEY_ID
      - NOTPROD_AWS_SECRET_ACCESS_KEY
      - NOTPROD_BUCKET
      - NOTPROD_START_DATE
      - NOTPROD_END_DATE
    when:
      event: push

  deploy_to_prod:
    image: quay.io/ukhomeofficedigital/kd
    environment:
      - KUBE_NAMESPACE=dq-apps
      - INSECURE_SKIP_TLS_VERIFY=true
    commands:
      - export KUBE_TOKEN=$$PROD_KUBE_TOKEN
      - export KUBE_SERVER=$$PROD_KUBE_SERVER
      - export AWS_ACCESS_KEY_ID=$$PROD_AWS_ACCESS_KEY_ID
      - export AWS_SECRET_ACCESS_KEY=$$PROD_AWS_SECRET_ACCESS_KEY
      - export BUCKET=$$PROD_BUCKET
      - export START_DATE=$$PROD_START_DATE
      - export END_DATE=$$PROD_START_DATE
      - kd -f secrets.yaml -f deployment.yaml
    secrets:
      - PROD_KUBE_TOKEN
      - PROD_KUBE_SERVER
      - PROD_AWS_ACCESS_KEY_ID
      - PROD_AWS_SECRET_ACCESS_KEY
      - PROD_BUCKET
      - PROD_START_DATE
      - PROD_END_DATE
    when:
      environment: production
      event: deployment
